### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by fxprunayre**
# 608

### Done

* Contact to resource -> translate "gmd:individualName" to "Kontakt zu Resource"
* Insert header "Zugriffsbeschränkungen (restriction d’accès) after field "Schlüsselwörter" (mots clés) (was already the case)
* Translate "gmd:SpatialRepresentation" to "Räumliche Auflösung"
* field "Vertriebsinformation / Bezeichnung" // "Empfohlene Werte - is it possible to delete OR disable & hide the dropdown-field?

> List removed even if it does not sound like a good idea. This is mandatory for ISO. Would be good to adapt the list to the format used in the project instead of living that to user inspiration.

* field "Vertriebsinformation / Protokoll" // "Empfohlene Werte" -> adaption of select-list possible?
*  field "Datenqualität / Bearbeitungsschritt" adapt select list

### Not done on purpose

*  Field "Basisinformation / Datumsangaben": implement field, that is automatically filled instead of textfield. This should be the same functionality, as it is implemented for the FeatureCatalogue Template

> In the FeatureCatalogue, the date stamp (ie. when the metadata is updated), here the date is the publication date of the resource. It can't be set automatically, it depends on the resource no ? The date stamp in ISO19139 is in the metadata section and is set automatically.

### Todo

* adapt select-list of field "Thematik":
ALKIS
Schutzgebiete
Planungsdaten (z.B. OSM Störer, Denkmale, ...)
Strassen und Wege
Oberflächendaten
Trassen
Hintergrunddaten (z.B: Orthophotos, TK's, ...)
weitere .... (TO Be COMPLETED!!!)

> We can't extend that list as it is defined by ISO (because it is an xsd:enumeration) and can't be extended. So option 
> 1) create a list of keyword in a thesaurus for that 
> 2) extend it anyway (even if not recommended)
> And provide the final list to be added.

# 616

### Done

* translate title of field "Kontakt für die Resource / gmd:individualName"

### Todo

* Field: "URL" (right above "Vertriebsinformation"): change the default from  "https://cb02bc.gpc-one.ts-icts.de?" is changed to DEV[1] and INT  [2]

>  Is this related to 1598 ?

* If possible delete field "Reference level" . AFAIK it is only mandatory required when the quality report is used. Quality report is only provided  for the MD of the data, since it basically refers to the data but not to the services.

> I would suggest to remove this from the template for service then.

# 633 / Done

* translate Field "Member name" to "Name des Attributs"
* translate Field "Type name" to "Feldtyp"
* translate header "Codelist" to "Werteliste"
* translate Field "Codelist / Label" to "Name"
* translate Field "Codelist / Code" to "Schlüssel"
* translate Field "Codelist / Definition" to "Werte Name"
* Feature Catalogue - if you look at the metadata in the standard-View, below linked datasources are listed twice under different headers: object catalogue (Objektartenkatalog) and other sources (andere Quellen) - is it possible to change?
* translate Field "gwc_lower" to "Reihenfolge" and check if it is possible, to make this field self-filling (sequential)

> This is lower cardinality. So 0 or 1 in most cases

# 1706 / Done

* When a link to other metadata-sets (e.g. service and/or feature catalogue) is set via the GNOS-surface when editing a metadata-set for "Data" the content of the field "Datumsfeld" is deleted.

> Not related to associated resource. Issue in the editor configuration. Improved the configuration to remove seconds in the date

# 1770 / Done

* When the file gco:lower is left empty validation fail, wghich is correct, because the field is mandatory. The field requires integer as input, if filled correctly, validation runs properly. In general the meaning and use of the filed is unclear.

> It is lower cardinality. So 0 for optional and 1 for mandatory fields.

# 1707 

### Todo

* Validating must be possible also if field "Metadaten / Organisation" is not filled.

> What is the main goal for the validation ? Conform to ISO (probably yes), to INSPIRE (probably not), to FTTH rules ? It is good to define the level of validation expected before hacking existing rules. It sounds that the minimum information to be populated for a contact is the organisation no ? so if this is an issue, I would say that a contact without org can be deleted no ?

# 1708 / Done

* Sometimes (sorry, no more detailed description possible up now) when inserting metadata, for some fields (e.g. "Vertriebsinformation / URL" and "Vertriebsinformation / Protokoll", see [1]as an example fields appear doubled
 

# 1598 / Done

Add possibility to do search & replace during harvesting.

## Example for testing:

Harvesting this record
https://sextant.ifremer.fr/geonetwork/srv/fre/xml.metadata.get?uuid=01051510-a178-11dc-8c36-000086f6a62e
which contains `http://www.rebent.org` URL in both `gmd:URL` and `gco:CharacterString`.

With the following configuration
image

Configuration for the XSL filter
`searchandreplace?search=http://www.rebent.org&replace=http://www.replaced.org`

Harvested record is:

image

with proper replacement of `http://www.rebent.org` by  `http://www.replaced.org`.

 # Other

* In date picker directive, hide seconds by setting the HTML date type step attribute to 60

image

* Translations added to GeoNetwork master too https://github.com/geonetwork/core-geonetwork/pull/3489 
* Removed default GN templates & samples
* Update with latest templates from FTTH
* Add patch to unplugged geOrchestra config
* Duplicate related items https://github.com/geonetwork/core-geonetwork/pull/3490

# Topic not covered in that PR which might be addressed

* Encoding of geometry type should not be done with https://github.com/cmangeat/core-geonetwork/blob/32727d1f9349d6aa9ae7dc32b175d0a552922ed3/schemas/iso19139/src/main/plugin/iso19139/loc/ger/codelists.xml#L1628-L1642 . A more standard approach is:
```
 <gmd:spatialRepresentationInfo>
      <gmd:MD_VectorSpatialRepresentation>
         <gmd:geometricObjects>
            <gmd:MD_GeometricObjects>
               <gmd:geometricObjectType>
                  <gmd:MD_GeometricObjectTypeCode codeList="http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/ML_gmxCodelists.xml#MD_GeometricObjectTypeCode"
                                                  codeListValue="point|curve|polygon"/>
               </gmd:geometricObjectType>
            </gmd:MD_GeometricObjects>
         </gmd:geometricObjects>
      </gmd:MD_VectorSpatialRepresentation>
   </gmd:spatialRepresentationInfo>
```

### CODE REVIEW

**Comment by tilladams** [comment]
Dear Francois and Chrostoph - I start to comment your changes in the FTTH-tickets (better place than here)

**Comment by tilladams** [comment]
I think you did code or configuration-changes for #GDI-1598 . Can you isolta this as a patch with a short "howto" insert this into any GNOs implementation?
Background: I hae two test-nodes running and would like to test this, but by just using the xslt filter as lined out above, it seems not to work

**Comment by cmangeat** [comment]
Path should be https://github.com/cmangeat/core-geonetwork/pull/1/commits/dc1ff7c68dab4302891dde75167cde988eec6f93

**Comment by fxprunayre** [comment]
> > It is lower cardinality. So 0 for optional and 1 for mandatory fields.

We could easily add suggestion list with 0/1 value:

image

If we want something more advanced, then a custom directive could be created to set:
* mandatory = lower=1/upper1
* optional = lower=0/upper1
* do we need to handle other cases ? 

This information is not displayed in default view mode.

**Pull request merged**
